# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45245768890c66c198f5005b7b92931c2ac7b4fb0ea1aad8f0aa1c6e210b87e1e94827bff503b7216de16ff77defcfa0fd3684521d80f47784af299593e416c6

test:
  secret_key_base: 3735e5c5864ade2a6614ee34a79d706d2c145576e95a6f2c60d120d95ddb3a52274c7fe10df86413a222f27489fd6d64b300816d07cd22e5158b72b7456e236f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
